name: ci

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.x'

      - name: install dependencies
        run: go mod download

      - name: run tests
        run: go test -coverprofile=coverage.out ./...

      - name: coveralls
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.out
          coveralls-endpoint: https://coveralls.io
          parallel: false
          coveralls-repo-token: ${{ secrets.COVERALLS_TOKEN }}

  sonarcloud:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
